services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - ./data/mongo:/data/db
  mongo-express:
    image: mongo-express:1
    restart: unless-stopped
    ports: ["8081:8081"]
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_BASICAUTH_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_BASICAUTH_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongo:27017/?authSource=admin
